CREATE CONSTRAINT ON (p:Project) ASSERT p.identifier IS UNIQUE;
CREATE CONSTRAINT ON (p:Project) ASSERT p.id IS UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.identifier IS UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.id IS UNIQUE;
CREATE CONSTRAINT ON (b:Booking) ASSERT b.id IS UNIQUE;
CREATE CONSTRAINT ON (r:RememberMe) ASSERT r.id IS UNIQUE;
CREATE CONSTRAINT ON (s:Session) ASSERT s.id IS UNIQUE;